### ISSUE TITLE
Extended fuse warning

### ISSUE THREAD

**Issue by ger-ator** [mysensors/ArduinoHwAVR#9]
Extended fuse should be 0xFE instead of 0x06. Avrdude complains about this when flashing bootloader on Sensebender Micro.

**Comment by sundberg84** [comment]
I can confirm this error - worked with 0xFE.

There is this note now from http://www.engbedded.com/fusecalc/

    Note that some numerical values refer to fuses containing undefined bits (set to '1' here). Depending on the target device these fuse bits will be read either as '0' or '1'. Verification errors will occur if the values are read back with undefined bits set to '0'. Everything is fine if the values read from the device are either the same as programmed, or the following values (undefined set to '0'): Extended: 0x06.

I have added a pull request for this change.

**Comment by tbowmo** [comment]
Could you bump the minor version as well [here]
(https://github.com/mysensors/ArduinoHwAVR/blob/e75b16f5341a4f3ff9cd318df848dbc8ec430f37/platform.txt#L9)

**Comment by tbowmo** [comment]
(And thanks for the PR :) )

**Comment by tekka007** [comment]
Fixed in #10
